# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1afa82b17cce9eeb6fac7c6053f972a669f7fab8fa6d8f1249f604d293e569d1d8dec149664f0afad6598dee2b432c2350d956669ce5b349a3cd1ce84b2b4ab

test:
  secret_key_base: 83f325299e5ecfa6c59f055867cd686522992ea012c02f77eb9f8277a5741504f10f14b8b4b143d4770717bffa93a576cf0b13fa226dab465b2cfe6c77cabbbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
